version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:45"
      timezone: "America/Chicago"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "[npm] frontend"
      include: "scope"
    open-pull-requests-limit: 10
     
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "thursday"
      timezone: "America/Chicago"
      time: "09:45"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "[npm] backend"
      include: "scope"
    open-pull-requests-limit: 10
