# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries: "*"
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "11:45"
      timezone: "America/Chicago"
    allow:
      - dependency-type: "all"
    target-branch: "main"
    commit-message:
      prefix: "[npm] "
      prefix-development: "[npm] dev"
      include: "scope"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
