version: 2

updates:

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "thursday"
      timezone: "America/Chicago"
      time: "9:00"
     commit-message:
      prefix: "[npm] frontend"
      include: "scope"
     open-pull-requests-limit: 10
     
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "thursday"
      timezone: "America/Chicago"
      time: "9:00"
     commit-message:
      prefix: "[npm] backend"
      include: "scope"
     open-pull-requests-limit: 10
