version: 2

updates:
  - package-ecosystem: "npm"
  	directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "8:40"
      timezone: "America/Chicago"
		labels:
      - "npm"
      - "dependencies"
      - "frontend"
		commit-message:
			prefix: "[npm] frontend"
			include: "scope"
		open-pull-request-limit: 10
      
  - package-ecosystem: "npm"
		directory: "/backend"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "8:40"
      timezone: "America/Chicago"
		labels:
      - "npm"
      - "dependencies"
      - "backend"
		commit-message:
      prefix: "[npm] backend"
      include: "scope"
		open-pull-request-limit: 10
